# Generated by Django 5.0.7 on 2024-07-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ph_no',
        ),
    ]
