# Generated by Django 5.0.7 on 2024-07-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.URLField()),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
