# Generated by Django 5.0.7 on 2024-07-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_home_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home_list',
        ),
        migrations.DeleteModel(
            name='UserManagement',
        ),
    ]
