# Generated by Django 5.0.7 on 2024-07-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_useroptions_delete_home_list_delete_usermanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
